config/routes.rb
SamsungSmarttvServer::Application.routes.draw do
  resources :widgets

  get 'widgetlist.xml' => 'widgets#index', :as => :widgetlistxml, :format => 'xml'

  root 'widgets#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  has_attached_file :package
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  def index
    @widgets = Widget.all
  end

  def show
  end

  def new
    @widget = Widget.new
  end

  def edit
  end

  def create
    @widget = Widget.new(widget_params)

    if @widget.save
      redirect_to @widget, notice: 'Widget was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @widget.update(widget_params)
      redirect_to @widget, notice: 'Widget was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @widget.destroy
    redirect_to widgets_url
  end

  private
    def set_widget
      @widget = Widget.find(params[:id])
    end

    def widget_params
      params.require(:widget).permit(:identifier, :title, :description, :package)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  def absolute_attachment_url(attachment_name)
    "#{request.protocol}#{request.host_with_port}#{attachment_name.url}"
  end
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'SmartTV Widget Server', root_path, class: 'brand' %>
      <ul class="nav">
        <li class="active"><%= link_to 'Widgets', widgets_path %></li>
        <li><%= link_to 'Widgetlist.xml', widgetlistxml_path %></li>
      </ul>
      <p class="navbar-text pull-right"><%= request.ip %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SamsungSmarttvServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/widgets/_form.html.erb
<%= form_for @widget, html: { multipart: true } do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :identifier %>
  <%= f.text_field :identifier %>

  <div><%= f.file_field :package %></div>

  <div class="btn-toolbar">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', widgets_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form' %>

app/views/widgets/index.html.erb
<h1>Widgets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>ID</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= link_to widget.title, widget %></td>
        <td><%= widget.description %></td>
        <td><%= widget.identifier %></td>
        <td>
          <%= link_to 'Edit', edit_widget_path(widget) %> |
          <%= link_to 'Delete', widget, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form' %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @widget.identifier %>
</p>

<p>
  <strong>Title:</strong>
  <%= @widget.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>